config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :recipes
  resources :ingredients

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :season
end

app/models/list_ingredient.rb
class ListIngredient < ApplicationRecord
  has_many :ingredients
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients, :through => :list_ingredient
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :ingredients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])
    @ingredient.save
  end

  def new
    @ingredients = Ingredient.new
  end

  def edit

  end

  def update
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @recipes = Recipe.all
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    @recipe.save
  end

  def new
    @recipes = Recipe.new
  end

  def edit
    @recipes = Recipe.find(params[:id])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipes = Recipe.find(params[:id])
    @recipe.update(params[:recipe])

    redirect_to recipes_path(@recipe)
  end

  def destroy
    @recipes = Recipe.find(params[:id])
    @recipes.destroy

    redirect_to recipes_path(@recipe)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/ingredients/edit.html.erb
<h1>change an ingredient</h1>

app/views/ingredients/index.html.erb
<h1>show all ingredients</h1>

app/views/ingredients/new.html.erb
<h1>create a new ingredient</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
 <link href="https://fonts.googleapis.com/css?family=Roboto:400,900&display=swap" rel="stylesheet">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
 <!-- bootstrap -->
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 <title>VipCook</title>
 <%= csrf_meta_tags %>
 <%= csp_meta_tag %>
 <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body>
   <%= render 'shared/navbar' %>
 <%= yield %>
<!--   <%= render 'shared/flashes' %>
  <%= render 'shared/footer' %>
 --><!--   ici y a du javascript tag qqlq chose-->
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/pages/home.html.erb
<h5>#Home</h5>
<div class='section_banner'>
  <div class="banner">
    <h3>WHAT ARE WE</h3>
    <h1>VIP-COOK <strong>Qu'est ce que c'est ?</strong></h1>
    <p>Pourquoi utiliser VIP-COOK ?</p>
    <h4>APP</h4>
    <ul>
      <li>Vous pouvez utiliser tous seul et répertoirier votre livre de recettes.</li>
      <li>Vous pouvez calculer tous vos cout de production par personnes</li>
      <li>Vous pouvez savoir si votre plat est Vegan / Vegetarien / de Saison</li>
    </ul>
    <h4>PROFIL</h4>
    <ul>
      <li>Vous pouvez faire la promo de votre recette</li>
      <li>Vous pouvez vendre votre technique</li>
      <li>Vous pouvez vendre vos plats dans votre région</li>
    </ul>
      <%= link_to "Cookbook", recipes_path %>
      <%= link_to "Télécharger", root_path %>
  </div>
</div>
<div class='section_content'>
  <div class="content">
    <h3>WHAT YOU DO</h3>
    <h1>Livre de recette</h1>
    <p>Remplir vos recettes et les gérer</p>
    <ul>
      <li>Calculer vos cout de production</li>
      <li>Définir prix de vente et calculer vos bénéfices</li>
      <li>Générer votre liste de courses</li>
      <li>Connaitre la saison de votre recette</li>
      <li>Impliquer les producteurs de votre région.</li>
    </ul>
    <%= link_to  "Créer une nouvelle Recette", new_recipe_path %>

  </div>
</div>
<div class="section_atout">
  <h3>HAVE AN IMPACT</h3>
  <h1>Ingrédients</h1>
    <p>Choisir parmi une large sélection d'ingrédients pré-enregisté ou ajouté les votres</p>
    <ul>
      <li>Générer votre liste de courses</li>
      <li>Connaitre la saison de votre recette</li>
      <li>Impliquer les producteurs de votre région.</li>
    </ul>
    <%= link_to 'ALL MY INGREDIENTS', ingredients_path %>
    <%= link_to 'ADD INGREDIENTS', new_ingredient_path %>
</div>

<div class="section_tool">
  <h3>BY THE WAY YOU DO IT</h3>
  <h1>Calcul de coût, liste de course</h1>
  <ul>
    <li>Définir prix de vente et calculer vos bénéfices</li>
  </ul>
</div>

<div class="section_contact">
  <h3>WHO WE ARE</h3>
  <div class="contact">
    <h3>Nous Contactez</h3>
  </div>

</div>

app/views/recipes/_form.html.erb
<!-- <%= render 'form', recipe: @recipe %> -->

<!-- ^this line is on /new.html.erb -->


<!-- <%= simple_form @recipe do |f| %>
  <%= f.input :title, :label => 'Votre pseudo' %>
  <%= f.input :menu_spot, hint: 'Ne doit pas contenir de chiffre' %>
  <%= f.input :wine, :as => :boolean %>
  <%= f.input :quantity_serving, :label => 'Votre pseudo' %>
  <%= f.input :time_cooking, :label => 'Votre pseudo' %>
  <%= f.input :time_prep, :label => 'Votre pseudo' %>
  <%= f.input :time_plating, :label => 'Votre pseudo' %>
  <%= f.input :time_marinade, :label => 'Votre pseudo' %>
  <%= f.input :price_waiting, :label => 'Votre pseudo' %>
  <%= f.input :price_serving, :label => 'Votre pseudo' %>
  <%= f.input :price_working, :label => 'Votre pseudo' %>
  <%= f.input :Total_time, :label => 'Votre pseudo' %>
  <%= f.input :Total_price, :label => 'Votre pseudo' %>

  <%= f.button :submit %>
<% end %>
 -->

app/views/recipes/edit.html.erb
<h1>recipes#edit</h1>

<%= render 'form', recipe: @recipe %>

app/views/recipes/index.html.erb
<h1>recipes#index</h1>

<% @recipes.each do |recipe| %>
<h5><%= recipe.title %></h5>
<p><%= recipe.description %></p>
<% end %>

app/views/recipes/new.html.erb
<h1>recipes#new</h1>


<p>here suppose to have a simple form for recipe_new</p>

app/views/recipes/show.html.erb
<h1>recipes#show</h1>

<h3><%= @recipe.title %></h3>
<p><%= @recipe.description %></p>

app/views/shared/_navbar.html.erb
<div class='section_menu'>
  <nav class="navbar sticky-top navbar-expand-lg navbar-custom">
    <div class="topnav">
      <%= link_to "Cookbook", recipes_path %>
      <%= link_to  "New Recipe", new_recipe_path %>
      <%= link_to "Home", root_path %>
      <%= link_to "Contact", new_rails_conductor_inbound_email_path %>

    </div>
  </nav>
</div>